ls:
  .dir: point.case
  .js: kebab-case
  .jsx: kebab-case
  .md: kebab-case
  .mdx: kebab-case
  .ts: kebab-case
  .tsx: kebab-case
  .d.ts: kebab-case
  .spec.ts: kebab-case
  .generated.ts: kebab-case
  .config.ts: point.case

ignore:
  - .cache
  - .eslintrc.js
  - .git
  - .github
  - .husky
  - dist
  - node_modules
  - SECURITY.md
  - test/e2e/node_modules
  - tmp
